// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostImage is the predicate function for postimage builders.
type PostImage func(*sql.Selector)

// Report is the predicate function for report builders.
type Report func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
