// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GreenTeaProgrammers/MatsuriSNS/ent/post"
	"github.com/GreenTeaProgrammers/MatsuriSNS/ent/postimage"
	"github.com/GreenTeaProgrammers/MatsuriSNS/ent/predicate"
)

// PostImageQuery is the builder for querying PostImage entities.
type PostImageQuery struct {
	config
	ctx        *QueryContext
	order      []postimage.OrderOption
	inters     []Interceptor
	predicates []predicate.PostImage
	withPost   *PostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostImageQuery builder.
func (piq *PostImageQuery) Where(ps ...predicate.PostImage) *PostImageQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *PostImageQuery) Limit(limit int) *PostImageQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *PostImageQuery) Offset(offset int) *PostImageQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *PostImageQuery) Unique(unique bool) *PostImageQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *PostImageQuery) Order(o ...postimage.OrderOption) *PostImageQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryPost chains the current query on the "post" edge.
func (piq *PostImageQuery) QueryPost() *PostQuery {
	query := (&PostClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postimage.Table, postimage.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, postimage.PostTable, postimage.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PostImage entity from the query.
// Returns a *NotFoundError when no PostImage was found.
func (piq *PostImageQuery) First(ctx context.Context) (*PostImage, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{postimage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *PostImageQuery) FirstX(ctx context.Context) *PostImage {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PostImage ID from the query.
// Returns a *NotFoundError when no PostImage ID was found.
func (piq *PostImageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{postimage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *PostImageQuery) FirstIDX(ctx context.Context) int {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PostImage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostImage entity is found.
// Returns a *NotFoundError when no PostImage entities are found.
func (piq *PostImageQuery) Only(ctx context.Context) (*PostImage, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{postimage.Label}
	default:
		return nil, &NotSingularError{postimage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *PostImageQuery) OnlyX(ctx context.Context) *PostImage {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PostImage ID in the query.
// Returns a *NotSingularError when more than one PostImage ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *PostImageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{postimage.Label}
	default:
		err = &NotSingularError{postimage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *PostImageQuery) OnlyIDX(ctx context.Context) int {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PostImages.
func (piq *PostImageQuery) All(ctx context.Context) ([]*PostImage, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryAll)
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PostImage, *PostImageQuery]()
	return withInterceptors[[]*PostImage](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *PostImageQuery) AllX(ctx context.Context) []*PostImage {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PostImage IDs.
func (piq *PostImageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryIDs)
	if err = piq.Select(postimage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *PostImageQuery) IDsX(ctx context.Context) []int {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *PostImageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryCount)
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*PostImageQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *PostImageQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *PostImageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryExist)
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *PostImageQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostImageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *PostImageQuery) Clone() *PostImageQuery {
	if piq == nil {
		return nil
	}
	return &PostImageQuery{
		config:     piq.config,
		ctx:        piq.ctx.Clone(),
		order:      append([]postimage.OrderOption{}, piq.order...),
		inters:     append([]Interceptor{}, piq.inters...),
		predicates: append([]predicate.PostImage{}, piq.predicates...),
		withPost:   piq.withPost.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *PostImageQuery) WithPost(opts ...func(*PostQuery)) *PostImageQuery {
	query := (&PostClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withPost = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostImage.Query().
//		GroupBy(postimage.FieldPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *PostImageQuery) GroupBy(field string, fields ...string) *PostImageGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PostImageGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = postimage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//	}
//
//	client.PostImage.Query().
//		Select(postimage.FieldPostID).
//		Scan(ctx, &v)
func (piq *PostImageQuery) Select(fields ...string) *PostImageSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &PostImageSelect{PostImageQuery: piq}
	sbuild.label = postimage.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PostImageSelect configured with the given aggregations.
func (piq *PostImageQuery) Aggregate(fns ...AggregateFunc) *PostImageSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *PostImageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !postimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *PostImageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostImage, error) {
	var (
		nodes       = []*PostImage{}
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withPost != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostImage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostImage{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withPost; query != nil {
		if err := piq.loadPost(ctx, query, nodes, nil,
			func(n *PostImage, e *Post) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *PostImageQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*PostImage, init func(*PostImage), assign func(*PostImage, *Post)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PostImage)
	for i := range nodes {
		fk := nodes[i].PostID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piq *PostImageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *PostImageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(postimage.Table, postimage.Columns, sqlgraph.NewFieldSpec(postimage.FieldID, field.TypeInt))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postimage.FieldID)
		for i := range fields {
			if fields[i] != postimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if piq.withPost != nil {
			_spec.Node.AddColumnOnce(postimage.FieldPostID)
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *PostImageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(postimage.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = postimage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostImageGroupBy is the group-by builder for PostImage entities.
type PostImageGroupBy struct {
	selector
	build *PostImageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *PostImageGroupBy) Aggregate(fns ...AggregateFunc) *PostImageGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *PostImageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, ent.OpQueryGroupBy)
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostImageQuery, *PostImageGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *PostImageGroupBy) sqlScan(ctx context.Context, root *PostImageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PostImageSelect is the builder for selecting fields of PostImage entities.
type PostImageSelect struct {
	*PostImageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *PostImageSelect) Aggregate(fns ...AggregateFunc) *PostImageSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *PostImageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, ent.OpQuerySelect)
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostImageQuery, *PostImageSelect](ctx, pis.PostImageQuery, pis, pis.inters, v)
}

func (pis *PostImageSelect) sqlScan(ctx context.Context, root *PostImageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
