// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GreenTeaProgrammers/MatsuriSNS/ent/post"
	"github.com/GreenTeaProgrammers/MatsuriSNS/ent/postimage"
)

// PostImage is the model entity for the PostImage schema.
type PostImage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID int `json:"post_id,omitempty"`
	// ImageURL holds the value of the "image_url" field.
	ImageURL string `json:"image_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostImageQuery when eager-loading is set.
	Edges        PostImageEdges `json:"edges"`
	post_images  *int
	selectValues sql.SelectValues
}

// PostImageEdges holds the relations/edges for other nodes in the graph.
type PostImageEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostImageEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostImage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postimage.FieldID, postimage.FieldPostID:
			values[i] = new(sql.NullInt64)
		case postimage.FieldImageURL:
			values[i] = new(sql.NullString)
		case postimage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case postimage.ForeignKeys[0]: // post_images
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostImage fields.
func (pi *PostImage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postimage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pi.ID = int(value.Int64)
		case postimage.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				pi.PostID = int(value.Int64)
			}
		case postimage.FieldImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_url", values[i])
			} else if value.Valid {
				pi.ImageURL = value.String
			}
		case postimage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pi.CreatedAt = value.Time
			}
		case postimage.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field post_images", value)
			} else if value.Valid {
				pi.post_images = new(int)
				*pi.post_images = int(value.Int64)
			}
		default:
			pi.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostImage.
// This includes values selected through modifiers, order, etc.
func (pi *PostImage) Value(name string) (ent.Value, error) {
	return pi.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostImage entity.
func (pi *PostImage) QueryPost() *PostQuery {
	return NewPostImageClient(pi.config).QueryPost(pi)
}

// Update returns a builder for updating this PostImage.
// Note that you need to call PostImage.Unwrap() before calling this method if this PostImage
// was returned from a transaction, and the transaction was committed or rolled back.
func (pi *PostImage) Update() *PostImageUpdateOne {
	return NewPostImageClient(pi.config).UpdateOne(pi)
}

// Unwrap unwraps the PostImage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pi *PostImage) Unwrap() *PostImage {
	_tx, ok := pi.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostImage is not a transactional entity")
	}
	pi.config.driver = _tx.drv
	return pi
}

// String implements the fmt.Stringer.
func (pi *PostImage) String() string {
	var builder strings.Builder
	builder.WriteString("PostImage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pi.ID))
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", pi.PostID))
	builder.WriteString(", ")
	builder.WriteString("image_url=")
	builder.WriteString(pi.ImageURL)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pi.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PostImages is a parsable slice of PostImage.
type PostImages []*PostImage
