// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GreenTeaProgrammers/MatsuriSNS/ent/post"
	"github.com/GreenTeaProgrammers/MatsuriSNS/ent/postimage"
)

// PostImageCreate is the builder for creating a PostImage entity.
type PostImageCreate struct {
	config
	mutation *PostImageMutation
	hooks    []Hook
}

// SetImageURL sets the "image_url" field.
func (pic *PostImageCreate) SetImageURL(s string) *PostImageCreate {
	pic.mutation.SetImageURL(s)
	return pic
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (pic *PostImageCreate) SetPostID(id int) *PostImageCreate {
	pic.mutation.SetPostID(id)
	return pic
}

// SetNillablePostID sets the "post" edge to the Post entity by ID if the given value is not nil.
func (pic *PostImageCreate) SetNillablePostID(id *int) *PostImageCreate {
	if id != nil {
		pic = pic.SetPostID(*id)
	}
	return pic
}

// SetPost sets the "post" edge to the Post entity.
func (pic *PostImageCreate) SetPost(p *Post) *PostImageCreate {
	return pic.SetPostID(p.ID)
}

// Mutation returns the PostImageMutation object of the builder.
func (pic *PostImageCreate) Mutation() *PostImageMutation {
	return pic.mutation
}

// Save creates the PostImage in the database.
func (pic *PostImageCreate) Save(ctx context.Context) (*PostImage, error) {
	return withHooks(ctx, pic.sqlSave, pic.mutation, pic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pic *PostImageCreate) SaveX(ctx context.Context) *PostImage {
	v, err := pic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pic *PostImageCreate) Exec(ctx context.Context) error {
	_, err := pic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pic *PostImageCreate) ExecX(ctx context.Context) {
	if err := pic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pic *PostImageCreate) check() error {
	if _, ok := pic.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "image_url", err: errors.New(`ent: missing required field "PostImage.image_url"`)}
	}
	if v, ok := pic.mutation.ImageURL(); ok {
		if err := postimage.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "PostImage.image_url": %w`, err)}
		}
	}
	return nil
}

func (pic *PostImageCreate) sqlSave(ctx context.Context) (*PostImage, error) {
	if err := pic.check(); err != nil {
		return nil, err
	}
	_node, _spec := pic.createSpec()
	if err := sqlgraph.CreateNode(ctx, pic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pic.mutation.id = &_node.ID
	pic.mutation.done = true
	return _node, nil
}

func (pic *PostImageCreate) createSpec() (*PostImage, *sqlgraph.CreateSpec) {
	var (
		_node = &PostImage{config: pic.config}
		_spec = sqlgraph.NewCreateSpec(postimage.Table, sqlgraph.NewFieldSpec(postimage.FieldID, field.TypeInt))
	)
	if value, ok := pic.mutation.ImageURL(); ok {
		_spec.SetField(postimage.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if nodes := pic.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postimage.PostTable,
			Columns: []string{postimage.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.post_images = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostImageCreateBulk is the builder for creating many PostImage entities in bulk.
type PostImageCreateBulk struct {
	config
	err      error
	builders []*PostImageCreate
}

// Save creates the PostImage entities in the database.
func (picb *PostImageCreateBulk) Save(ctx context.Context) ([]*PostImage, error) {
	if picb.err != nil {
		return nil, picb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(picb.builders))
	nodes := make([]*PostImage, len(picb.builders))
	mutators := make([]Mutator, len(picb.builders))
	for i := range picb.builders {
		func(i int, root context.Context) {
			builder := picb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, picb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, picb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, picb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (picb *PostImageCreateBulk) SaveX(ctx context.Context) []*PostImage {
	v, err := picb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (picb *PostImageCreateBulk) Exec(ctx context.Context) error {
	_, err := picb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (picb *PostImageCreateBulk) ExecX(ctx context.Context) {
	if err := picb.Exec(ctx); err != nil {
		panic(err)
	}
}
